export const strings = {
  en: {
    welcome: 'Welcome',
    home: 'Home',
    prices: 'Prices',
    scan: 'Scan',
    requests: 'Requests',
    profile: 'Profile',
    findProduce: 'Find Produce',
    myListings: 'My Listings',
    agriShops: 'Agri Shops',
    myOrders: 'My Orders',
    postRequest: 'Post Request',
    notifications: 'Notifications',
    login: 'Login',
    logout: 'Logout',
  },
  si: {
    welcome: 'ආයුබෝවන්',
    home: 'මුල් පිටුව',
    prices: 'මිල ගණන්',
    scan: 'ස්කෑන් කරන්න',
    requests: 'ඉල්ලීම්',
    profile: 'ගිණුම',
    findProduce: 'අස්වැන්න සොයන්න',
    myListings: 'මගේ ලැයිස්තුගත කිරීම්',
    agriShops: 'කෘෂි සාප්පු',
    myOrders: 'මගේ ඇණවුම්',
    postRequest: 'ඉල්ලීමක් පළ කරන්න',
    notifications: 'දැනුම්දීම්',
    login: 'ඇතුල් වන්න',
    logout: 'පිට වන්න',
  },
  ta: {
    welcome: 'வரவேற்கிறோம்',
    home: 'முகப்பு',
    prices: 'விலைகள்',
    scan: 'ஸ்கேன் செய்',
    requests: 'கோரிக்கைகள்',
    profile: 'சுயவிவரம்',
    findProduce: 'விளைபொருட்களை தேடு',
    myListings: 'எனது பட்டியல்கள்',
    agriShops: 'விவசாய கடைகள்',
    myOrders: 'எனது ஆர்டர்கள்',
    postRequest: 'கோரிக்கையை இடு',
    notifications: 'அறிவிப்புகள்',
    login: 'உள்நுழை',
    logout: 'வெளியேறு',
  },
};
